name: Validate & Deploy 
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Validate
        uses: kestra-io/validate-action@develop
        with:
          resource: flow
          directory: kestra/flows
          server: ${{ secrets.KESTRA_INST_ADDR }}
          user: ${{secrets.KESTRA_USER}}
          password: ${{ secrets.KESTRA_PWD }}
      - name: Deploy
        uses: kestra-io/deploy-action@master
        with:
          namespace: company.team
          resource: flow
          directory: kestra/flows
          server: ${{ secrets.KESTRA_INST_ADDR }}
          user: ${{secrets.KESTRA_USER}}
          password: ${{ secrets.KESTRA_PWD }}
      

